### ISSUE TITLE
Investigate why tests are so slow

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckanext-datapackager#32]
They used to be much faster

**Comment by vitorbaptista** [comment]
The culprit seems to be HTTPretty

**Comment by k-nut** [comment]
Upgrading to the latest version of httpretty (0.8.14) make the tests run much faster but almost all of them fail with errors like this one:
```
======================================================================
ERROR: ckanext.datapackager.tests.logic.action.test_create.TestPackageCreateFromDataPackage.test_it_uploads_resources_with_inline_strings_as_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/httpretty/core.py", line 1146, in wrapper
    return test(*args, **kw)
  File "/Users/knut/viderum/ckanext-datapackager/ckanext/datapackager/tests/logic/action/test_create.py", line 163, in test_it_uploads_resources_with_inline_strings_as_data
    helpers.call_action('package_create_from_datapackage', url=url)
  File "/Users/knut/viderum/ckan/ckan/tests/helpers.py", line 105, in call_action
    return logic.get_action(action_name)(context=context, data_dict=kwargs)
  File "/Users/knut/viderum/ckan/ckan/logic/__init__.py", line 423, in wrapped
    result = _action(context, data_dict, **kw)
  File "/Users/knut/viderum/ckanext-datapackager/ckanext/datapackager/logic/action/create.py", line 61, in package_create_from_datapackage
    res = _package_create_with_unique_name(context, dataset_dict, name)
  File "/Users/knut/viderum/ckanext-datapackager/ckanext/datapackager/logic/action/create.py", line 104, in _package_create_with_unique_name
    res = toolkit.get_action('package_create')(context, dataset_dict)
  File "/Users/knut/viderum/ckan/ckan/logic/__init__.py", line 423, in wrapped
    result = _action(context, data_dict, **kw)
  File "/Users/knut/viderum/ckan/ckan/logic/action/create.py", line 229, in package_create
    else _get_action('package_show')(context, {'id': context['id']})
  File "/Users/knut/viderum/ckan/ckan/logic/__init__.py", line 423, in wrapped
    result = _action(context, data_dict, **kw)
  File "/Users/knut/viderum/ckan/ckan/logic/action/get.py", line 955, in package_show
    search_result = search.show(name_or_id)
  File "/Users/knut/viderum/ckan/ckan/lib/search/__init__.py", line 239, in show
    return package_query.get_index(package_reference)
  File "/Users/knut/viderum/ckan/ckan/lib/search/query.py", line 270, in get_index
    solr_response = conn.search(**query)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/pysolr.py", line 699, in search
    response = self._select(params)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/pysolr.py", line 406, in _select
    return self._send_request('get', path)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/pysolr.py", line 369, in _send_request
    timeout=self.timeout)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
  File "/Users/knut/.virtualenvs/ckan/lib/python2.7/site-packages/httpretty/core.py", line 323, in connect
    raise UnmockedError()
UnmockedError: No mocking was registered, and real connections are not allowed (httpretty.allow_net_connect = False).
```

**Comment by k-nut** [comment]
When I set `httpretty.HTTPretty.allow_net_connect = True` in a test I get a different error:
```
SearchIndexError: Solr returned an error: (u'Failed to connect to server at \'http://127.0.0.1:8983/solr/ckan/update/?commit=true\', are you sure that URL is correct? Checking it in a browser might help: (\'Connection aborted.\', BadStatusLine("\'\'",))',)
```
So now this makes sense. We tried to make another request to solr but did not register a response for that request. Therefore it is failing.

**Comment by amercader** [comment]
@k-nut See this for the Solr failure https://github.com/ckan/ckanext-harvest/commit/cbd65a63efe6e5943d87fa82e0a1176f11d8b470

**Comment by k-nut** [comment]
@amercader the problem is that the tests fail locally as well.

And locally solr does work. It seems to be that even when specifying  `httpretty.HTTPretty.allow_net_connect = True` httpretty still goes in there and stops us from making an actual request to solr. When I take httpretty out of the test and actually return the json file from a local server instead of letting httpretty mock it it works fine...

```
    def test_it_allows_changing_dataset_visibility(self):
        user = factories.Sysadmin()
        organization = factories.Organization()

        url = 'http://localhost:8000/datapackage.json'
        dataset = helpers.call_action('package_create_from_datapackage',
                                      context={'user': user['id']},
                                      url=url,
                                      owner_org=organization['id'],
                                      private='true')
        nose.tools.assert_true(dataset['private'])
```
No solr issues with this test case (where the only difference is that I have a `SimpleHTTPServer` running which returns the desired json instead of letting httpretty do that...)

**Comment by k-nut** [comment]
So the error that we get with solr is known and documented here: https://github.com/gabrielfalcao/HTTPretty/issues/65 

People there proposed using https://github.com/getsentry/responses or https://github.com/patrys/httmock but those seem to be requetst only. Will investigate further.

**Comment by k-nut** [comment]
I think we are pretty stuck with this situation. @vitorbaptista did the tests ever actually work with httpretty? Looking at the [build history](https://travis-ci.org/ckan/ckanext-datapackager/builds) it seems like they have been failing for the last couple of months...

**Comment by k-nut** [comment]
Just to document further: The responses library is also no alternative because it also catches all or nothing and we would only like to catch some requests (the datapackager requests, not the solr requests)

**Comment by k-nut** [comment]
🎉 so turns out we could use [`requests-mock`](https://requests-mock.readthedocs.io/) This is specifically written to mock the `requests` module which `datapackage` fortunately uses internally. It has a `real_http` option which forwards non mocked requests which is exactly what we want.

If no one tells me otherwise I will rewrite all the tests to use this library instead of httpretty.

Example:

```
    @requests_mock.Mocker(real_http=True)
    def test_it_allows_changing_dataset_visibility(self, mock_requests):
        url = 'http://www.somewhere.com/datapackage.json'
        datapackage = {
            'name': 'foo',
        }
        mock_requests.register_uri('GET', url, json=datapackage)

        user = factories.Sysadmin()
        organization = factories.Organization()
        dataset = helpers.call_action('package_create_from_datapackage',
                                      context={'user': user['id']},
                                      url=url,
                                      owner_org=organization['id'],
                                      private='true')
        nose.tools.assert_true(dataset['private'])
```

**Comment by pwalsh** [comment]
@k-nut I think you can hold on this issue now. Sounds like it is taking some time, for not a lot of real benefit right now.

**Comment by k-nut** [comment]
@pwalsh I think having a passing build is quite important. Since I figured out how to solve this and it was not that much work I created #47 which replaces httpretty. Now we do not have to fear to break something without realizing it anymore.
